apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost-001
  namespace: calculator
selector:
  matchLabels:
    app: calculator-api
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: calculator-api
        fixedResources:
          limits: 300m
          requests: 300m
  durationPolicy:
    # fixedDuration:
    #   unit: Seconds
    #   value: 60
    podCondition:
      type: Ready
      status: "True"
