apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
  labels:
    app: calculator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
        - name: calculator-api
          image: tresende/calculator-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
            requests:
              cpu: "500m"
