apiVersion: v1
kind: Service
metadata:
  name: calculator-api-service
spec:
  selector:
    app: calculator-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
