apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
  namespace: calculator
  labels:
    app: calculator-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: calculator-api
          image: tresende/calculator-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "150m"
            requests:
              cpu: "150m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
