apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
  namespace: calculator
  labels:
    app: calculator-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
      annotations:
        startupcpu.boost.kubernetes.io/enabled: "true" # Habilita o boost
    spec:
      containers:
        - name: calculator-api
          image: tresende/calculator-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "150m"
            requests:
              cpu: "150m"
